version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm ci
workflows:
  version: 2
  build:
    jobs:
      - build-and-test