version: 2
jobs:
  node10:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm ci
      - run: echo node 10 job finished successfully

  node13:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm ci
      - run: echo node 10 job finished successfully

workflows:
  version: 2
  build:
    jobs:
      - node10
      - node13