version: 2

jobs:
  node10:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm run ci
      - run:
          command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
          environment:
            COVERALLS_SERVICE_NAME: circle-ci
            COVERALLS_GIT_BRANCH: ${CIRCLE_BRANCH}
      - run: ls -la
      - run: echo node 10 job finished successfully

  node13:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm run ci
      - run: ls -la
      - run: echo node 13 job finished successfully

  compliance:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: compliance check
          command: |
            pip3 install --user reuse
            ~/.local/bin/reuse lint

  deploy-npm:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm run ci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ls -la
      - run:
          name: Publish package
          command: npm publish --access public
      - run: echo Deploy to NPM finished successfully

workflows:
  version: 2
  build:
    jobs:
      - node10
      - node13
      - compliance
  deploy:
    jobs:     
      - deploy-npm:          
          filters: # <<< Deploy only Tags
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/          
