version: 2

jobs:
  node10:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm run ci
      - run: ls -la
      - run: echo node 10 job finished successfully

  node13:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm run ci
      - run: ls -la
      - run: echo node 13 job finished successfully

  deploy-npm:
    docker:
      - image: circleci/node:10.19
    working_directory: ~/repo    
    steps:
      - checkout      
      - run: npm install            
      - run: npm run ci
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ls -la
      - run:
          name: Publish package
          command: npm publish --access public
      - run: echo Deploy to NPM finished successfully

workflows:
  version: 2
  build:
    jobs:
      - node10
      - node13
  deploy:
    jobs:
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval
      - deploy-npm:
          filters: # <<< Deploy only Tags
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires: # <<< Deploy only after manual approval
            - hold
